# Generated by Django 3.0.1 on 2020-03-04 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='套装名称')),
            ],
            options={
                'verbose_name': '套装',
                'verbose_name_plural': '套装',
            },
        ),
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dict_type', models.CharField(max_length=255, verbose_name='字典类型')),
                ('dict_name', models.CharField(max_length=255, verbose_name='字典名称')),
                ('dict_value', models.CharField(max_length=255, verbose_name='字典值')),
            ],
            options={
                'verbose_name': '字典',
                'verbose_name_plural': '字典',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='部件名称')),
                ('weight', models.IntegerField(default=1, verbose_name='部件权重')),
                ('collection', models.ForeignKey(blank=True, db_column='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='lottery.Collection', verbose_name='套装')),
            ],
            options={
                'verbose_name': '部件',
                'verbose_name_plural': '部件',
            },
        ),
    ]
