# Generated by Django 3.0.1 on 2020-03-07 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='稀有度名称')),
                ('weight', models.IntegerField(verbose_name='稀有度权重')),
            ],
            options={
                'verbose_name': '稀有度',
                'verbose_name_plural': '稀有度',
            },
        ),
        migrations.DeleteModel(
            name='Dictionary',
        ),
        migrations.AddField(
            model_name='item',
            name='rarity',
            field=models.ForeignKey(blank=True, db_column='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='lottery.Rarity', verbose_name='稀有度'),
        ),
    ]
