# Generated by Django 3.0.1 on 2020-03-08 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0004_auto_20200308_0206'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qq', models.CharField(max_length=20, verbose_name='qq号')),
                ('time', models.DateTimeField()),
                ('collection', models.ForeignKey(db_column='', on_delete=django.db.models.deletion.PROTECT, to='lottery.Collection', verbose_name='套装')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qq', models.CharField(max_length=20, verbose_name='qq号')),
                ('time', models.DateTimeField()),
                ('item', models.ForeignKey(db_column='', on_delete=django.db.models.deletion.PROTECT, to='lottery.Item', verbose_name='部件')),
            ],
        ),
    ]
